#!/usr/bin/env bash
# ============================================================================
#  🚀 DEPLOY SCRIPT — Anchor Point Advising
# ============================================================================
#  Usage:
#    bash scripts/deploy.sh                    — Full deploy (backend + frontend)
#    bash scripts/deploy.sh backend            — Deploy backend only
#    bash scripts/deploy.sh frontend           — Deploy frontend only
#    bash scripts/deploy.sh all                — Deploy everything (default)
#    bash scripts/deploy.sh --status           — Show deployment status
#    bash scripts/deploy.sh --rollback         — Rollback to previous commit
#    bash scripts/deploy.sh --quick            — Quick deploy (pull + restart only)
#
#  Config:
#    Reads from ~/.server-setup.conf if available.
#    Override with environment variables.
# ============================================================================

set -euo pipefail

# ── Colors & Logging ────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

log()      { echo -e "  ${DIM}[$(date +"%H:%M:%S")]${NC} $1"; }
log_ok()   { echo -e "  ${GREEN}✅ $1${NC}"; }
log_warn() { echo -e "  ${YELLOW}⚠️  $1${NC}"; }
log_fail() { echo -e "  ${RED}❌ $1${NC}"; }
log_info() { echo -e "  ${CYAN}ℹ  $1${NC}"; }
separator() { echo -e "  ${DIM}───────────────────────────────────────────────${NC}"; }

# ── Auto-load config ────────────────────────────────────────────────────

CONFIG_FILE="${CONFIG_FILE:-$HOME/.server-setup.conf}"
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
    log_ok "Loaded config from $CONFIG_FILE"
fi

# ── Defaults ────────────────────────────────────────────────────────────
# Derive from config or use sane defaults

PROJECT_DIR="${PROJECT_DIR:-$HOME/anchor-point}"
APP_NAME="${APP_NAME:-anchor-point}"
GIT_BRANCH="${GIT_BRANCH:-main}"
BACKEND_DIR="${BACKEND_DIR:-$PROJECT_DIR/backend}"
FRONTEND_DIR="${FRONTEND_DIR:-$PROJECT_DIR}"
BACKEND_PORT="${BACKEND_PORT:-3012}"
FRONTEND_PORT="${FRONTEND_PORT:-3011}"
DEPLOY_TARGET="${1:-all}"
LOGFILE="${LOGFILE:-$PROJECT_DIR/deploy.log}"
DOMAIN_NAME="${DOMAIN_NAME:-}"

BE_PM2_NAME="${APP_NAME}"
FE_PM2_NAME="${APP_NAME}-frontend"

# ── Validate ────────────────────────────────────────────────────────────

validate() {
    if [[ -z "$PROJECT_DIR" || ! -d "$PROJECT_DIR" ]]; then
        log_fail "PROJECT_DIR not found: $PROJECT_DIR"
        log_info "Run server-setup.sh first, or export PROJECT_DIR."
        exit 1
    fi
}

# ── Env File Management ────────────────────────────────────────────────

ensure_env_files() {
    log "📄 Checking environment files..."

    # ── Frontend .env.local ──────────────────────────────────────────
    # Regenerated on every deploy to match current server config.
    local fe_env="$FRONTEND_DIR/.env.local"
    local api_url="http://localhost:${BACKEND_PORT}"
    if [[ -n "$DOMAIN_NAME" ]]; then
        api_url="https://${DOMAIN_NAME}"
    fi

    cat > "$fe_env" <<FEENV
# Auto-generated by deploy.sh — do NOT edit on server.
# Change values in ~/.server-setup.conf and re-deploy.
BACKEND_URL=${api_url}
NEXT_PUBLIC_BASE_URL=${DOMAIN_NAME:+https://$DOMAIN_NAME}
FEENV
    log_ok "Frontend .env.local written (BACKEND_URL=${api_url})"

    # ── Backend .env (validate, NEVER overwrite) ─────────────────────
    local be_env="$BACKEND_DIR/.env"
    if [[ ! -f "$be_env" ]]; then
        log_fail "Backend .env not found at $be_env"
        log_fail "Create it manually — see docs/DEPLOYMENT_TUTORIAL.md"
        return 1
    fi

    # Validate critical variables exist
    local missing=0
    for var in DATABASE_URL JWT_SECRET PORT; do
        if ! grep -q "^${var}=" "$be_env" 2>/dev/null; then
            log_fail "Missing $var in $be_env"
            ((missing++))
        fi
    done
    if [[ $missing -gt 0 ]]; then
        return 1
    fi

    # Ensure FRONTEND_URL is set correctly for CORS
    if grep -q "^FRONTEND_URL=" "$be_env"; then
        log_ok "Backend .env validated ($be_env)"
    else
        log_warn "FRONTEND_URL not found in backend .env — CORS may fail"
    fi
}

# ── Git Pull ────────────────────────────────────────────────────────────

deploy_pull() {
    log "📥 Pulling latest code..."
    cd "$PROJECT_DIR" || { log_fail "Cannot cd to $PROJECT_DIR"; exit 1; }

    # Save current commit for rollback
    git rev-parse HEAD > "$PROJECT_DIR/.last-deploy-commit"

    git fetch origin
    local current_branch
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if [[ "$current_branch" != "$GIT_BRANCH" ]]; then
        log_info "Switching from '$current_branch' → '$GIT_BRANCH'..."
        git checkout "$GIT_BRANCH" || { log_fail "Failed to checkout: $GIT_BRANCH"; exit 1; }
    fi

    git reset --hard "origin/$GIT_BRANCH"
    log_ok "Code synced to origin/$GIT_BRANCH"

    local commit_info
    commit_info=$(git log -1 --format="%h — %s (%an, %ar)")
    log_info "Latest commit: $commit_info"
}

# ── Backend Deploy ──────────────────────────────────────────────────────

deploy_backend() {
    echo ""
    echo -e "  ${CYAN}${BOLD}━━━ 🔧 BACKEND DEPLOY ━━━${NC}"
    echo ""
    echo "" >> "$LOGFILE"
    echo "=== BACKEND DEPLOY $(date) ===" >> "$LOGFILE"

    if [[ ! -d "$BACKEND_DIR" ]]; then
        log_fail "Backend directory not found: $BACKEND_DIR"
        return 1
    fi

    cd "$BACKEND_DIR"

    # ── Dependencies ────────────────────────────────────────────────
    log "📦 Installing backend dependencies..."
    npm install 2>&1 | tail -5 | tee -a "$LOGFILE"
    log_ok "Dependencies installed."

    # ── Prisma ──────────────────────────────────────────────────────
    log "🔗 Generating Prisma client..."
    npx prisma generate 2>&1 | tee -a "$LOGFILE"
    log_ok "Prisma client generated."

    log "🗄️  Running Prisma migrations (deploy — production safe)..."
    if npx prisma migrate deploy 2>&1 | tee -a "$LOGFILE"; then
        log_ok "Migrations applied."
    else
        log_warn "Migration returned non-zero. Check if expected."
    fi

    # ── Build ───────────────────────────────────────────────────────
    log "🔨 Building NestJS backend..."
    rm -rf dist tsconfig.build.tsbuildinfo tsconfig.tsbuildinfo

    set -o pipefail
    if ! npm run build 2>&1 | tee -a "$LOGFILE"; then
        log_fail "Backend build FAILED — keeping old PM2 process."
        set +o pipefail
        return 1
    fi
    set +o pipefail

    # ── Verify build output ─────────────────────────────────────────
    if [[ ! -f "dist/main.js" && ! -f "dist/src/main.js" ]]; then
        log_fail "Build produced no output (dist/main.js missing) — NOT restarting PM2."
        return 1
    fi
    log_ok "Backend build verified."

    # ── PM2 Restart ─────────────────────────────────────────────────
    log "🔄 Restarting PM2 process: $BE_PM2_NAME..."
    if pm2 describe "$BE_PM2_NAME" &>/dev/null; then
        pm2 restart "$BE_PM2_NAME" --update-env
        log_ok "Backend PM2 process restarted."
    else
        log_warn "PM2 process '$BE_PM2_NAME' not found — starting fresh..."
        cd "$BACKEND_DIR"
        pm2 start npm --name "$BE_PM2_NAME" -- run start:prod
        log_ok "Backend started under PM2."
    fi

    # ── Verify ──────────────────────────────────────────────────────
    sleep 3
    if pm2 pid "$BE_PM2_NAME" | grep -q '[0-9]'; then
        log_ok "Backend is online ✓"
    else
        log_fail "Backend is not running — check: pm2 logs $BE_PM2_NAME --lines 50"
        return 1
    fi
    separator
}

# ── Frontend Deploy ─────────────────────────────────────────────────────

deploy_frontend() {
    echo ""
    echo -e "  ${CYAN}${BOLD}━━━ 🎨 FRONTEND DEPLOY ━━━${NC}"
    echo ""
    echo "" >> "$LOGFILE"
    echo "=== FRONTEND DEPLOY $(date) ===" >> "$LOGFILE"

    if [[ ! -d "$FRONTEND_DIR" ]]; then
        log_fail "Frontend directory not found: $FRONTEND_DIR"
        return 1
    fi

    cd "$FRONTEND_DIR"

    # ── Dependencies ────────────────────────────────────────────────
    log "📦 Installing frontend dependencies..."
    npm install 2>&1 | tail -5 | tee -a "$LOGFILE"
    log_ok "Dependencies installed."

    # ── Clear caches and build ──────────────────────────────────────
    log "🧹 Clearing Next.js caches..."
    rm -rf .next/cache

    log "🔨 Building Next.js frontend (this may take 1–3 minutes)..."
    set -o pipefail
    if ! npm run build 2>&1 | tail -20 | tee -a "$LOGFILE"; then
        log_fail "Frontend build FAILED — keeping old PM2 process."
        set +o pipefail
        return 1
    fi
    set +o pipefail
    log_ok "Frontend build complete."

    # ── PM2 Restart ─────────────────────────────────────────────────
    log "🔄 Restarting PM2 process: $FE_PM2_NAME..."
    if pm2 describe "$FE_PM2_NAME" &>/dev/null; then
        pm2 restart "$FE_PM2_NAME" --update-env
        log_ok "Frontend PM2 process restarted."
    else
        log_warn "PM2 process '$FE_PM2_NAME' not found — starting fresh..."
        cd "$FRONTEND_DIR"
        PORT=$FRONTEND_PORT pm2 start npm --name "$FE_PM2_NAME" -- run start
        log_ok "Frontend started under PM2."
    fi

    # ── Verify ──────────────────────────────────────────────────────
    sleep 3
    if pm2 pid "$FE_PM2_NAME" | grep -q '[0-9]'; then
        log_ok "Frontend is online ✓"
    else
        log_fail "Frontend is not running — check: pm2 logs $FE_PM2_NAME --lines 50"
        return 1
    fi
    separator
}

# ── Health Check ────────────────────────────────────────────────────────

health_check() {
    echo ""
    echo -e "  ${CYAN}${BOLD}━━━ 🏥 HEALTH CHECK ━━━${NC}"
    echo ""

    local passed=0 failed=0

    # Backend API health
    log "Checking backend on port $BACKEND_PORT..."
    local http_code
    http_code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 \
        "http://127.0.0.1:${BACKEND_PORT}/api/" 2>/dev/null || echo "000")

    if [[ "$http_code" =~ ^[23] ]]; then
        log_ok "Backend: HTTP $http_code ✓"
        ((passed++))
    elif [[ "$http_code" == "404" ]]; then
        log_ok "Backend: HTTP 404 (responding, no root route — normal) ✓"
        ((passed++))
    else
        log_warn "Backend: HTTP $http_code"
        ((failed++))
    fi

    # Frontend health
    log "Checking frontend on port $FRONTEND_PORT..."
    http_code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 \
        "http://127.0.0.1:${FRONTEND_PORT}/" 2>/dev/null || echo "000")

    if [[ "$http_code" =~ ^[23] ]]; then
        log_ok "Frontend: HTTP $http_code ✓"
        ((passed++))
    else
        log_warn "Frontend: HTTP $http_code (may still be starting)"
        ((failed++))
    fi

    # External (via Nginx / domain)
    if [[ -n "$DOMAIN_NAME" ]]; then
        log "Checking HTTPS on $DOMAIN_NAME..."
        http_code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 \
            "https://${DOMAIN_NAME}/" 2>/dev/null || echo "000")

        if [[ "$http_code" =~ ^[23] ]]; then
            log_ok "HTTPS: HTTP $http_code 🔒 ✓"
            ((passed++))
        else
            log_warn "HTTPS: HTTP $http_code"
            ((failed++))
        fi
    fi

    echo ""
    if [[ $failed -eq 0 ]]; then
        log_ok "All health checks passed ($passed/$((passed + failed)))"
    else
        log_warn "$passed passed, $failed failed"
    fi
}

# ── Quick Deploy ────────────────────────────────────────────────────────

do_quick_deploy() {
    echo -e "\n  ${CYAN}${BOLD}━━━ ⚡ QUICK DEPLOY ━━━${NC}\n"
    echo "" >> "$LOGFILE"
    echo "=== QUICK DEPLOY $(date) ===" >> "$LOGFILE"

    deploy_pull

    log "🔄 Restarting all PM2 processes..."
    if pm2 describe "$BE_PM2_NAME" &>/dev/null; then
        pm2 restart "$BE_PM2_NAME" --update-env
        log_ok "Backend restarted."
    fi
    if pm2 describe "$FE_PM2_NAME" &>/dev/null; then
        pm2 restart "$FE_PM2_NAME" --update-env
        log_ok "Frontend restarted."
    fi

    pm2 save
    sleep 3
    health_check

    echo ""
    echo -e "  ${GREEN}${BOLD}⚡ Quick deploy complete!${NC}"
    echo ""
}

# ── Rollback ────────────────────────────────────────────────────────────

do_rollback() {
    echo -e "\n  ${YELLOW}${BOLD}━━━ ⏪ ROLLBACK ━━━${NC}\n"
    echo "" >> "$LOGFILE"
    echo "=== ROLLBACK $(date) ===" >> "$LOGFILE"

    cd "$PROJECT_DIR"
    local rollback_file="$PROJECT_DIR/.last-deploy-commit"

    if [[ ! -f "$rollback_file" ]]; then
        log_fail "No previous deployment found. Cannot rollback."
        return 1
    fi

    local prev_commit
    prev_commit=$(cat "$rollback_file")
    local current_commit
    current_commit=$(git rev-parse --short HEAD)

    log "Current: $current_commit"
    log "Rolling back to: $(echo "$prev_commit" | cut -c1-7)"

    git checkout "$prev_commit"
    log_ok "Checked out previous commit."

    # Rebuild backend
    cd "$BACKEND_DIR"
    log "📦 Reinstalling backend dependencies..."
    npm install
    npx prisma generate
    npm run build
    pm2 restart "$BE_PM2_NAME" --update-env

    # Rebuild frontend
    cd "$FRONTEND_DIR"
    log "📦 Reinstalling frontend dependencies..."
    npm install
    rm -rf .next/cache
    npm run build
    pm2 restart "$FE_PM2_NAME" --update-env

    pm2 save
    sleep 3
    health_check

    rm -f "$rollback_file"

    echo ""
    echo -e "  ${YELLOW}${BOLD}⏪ Rollback complete!${NC}"
    echo -e "  ${DIM}  Now at: $(git rev-parse --short HEAD)${NC}"
    echo ""
}

# ── Status ──────────────────────────────────────────────────────────────

do_status() {
    echo -e "\n  ${CYAN}${BOLD}━━━ 📋 DEPLOYMENT STATUS ━━━${NC}\n"
    cd "$PROJECT_DIR"

    echo -e "  ${BOLD}App Name  :${NC} $APP_NAME"
    echo -e "  ${BOLD}Branch    :${NC} $GIT_BRANCH"
    echo -e "  ${BOLD}Commit    :${NC} $(git rev-parse --short HEAD)"
    echo -e "  ${BOLD}Message   :${NC} $(git log -1 --pretty=format:"%s")"
    echo -e "  ${BOLD}Date      :${NC} $(git log -1 --pretty=format:"%ci")"
    echo -e "  ${BOLD}Domain    :${NC} ${DOMAIN_NAME:-<not set>}"
    echo ""
    echo -e "  ${BOLD}Ports:${NC}"
    echo -e "  ${DIM}  Backend  : $BACKEND_PORT${NC}"
    echo -e "  ${DIM}  Frontend : $FRONTEND_PORT${NC}"
    echo ""
    echo -e "  ${BOLD}PM2 Status:${NC}"

    local be_status fe_status
    be_status=$(pm2 jlist 2>/dev/null | grep -o "\"name\":\"${BE_PM2_NAME}\"[^}]*\"status\":\"[^\"]*\"" | grep -o '"status":"[^"]*"' | cut -d'"' -f4 || echo "not found")
    fe_status=$(pm2 jlist 2>/dev/null | grep -o "\"name\":\"${FE_PM2_NAME}\"[^}]*\"status\":\"[^\"]*\"" | grep -o '"status":"[^"]*"' | cut -d'"' -f4 || echo "not found")

    echo -e "  ${DIM}  Backend  ($BE_PM2_NAME): $be_status${NC}"
    echo -e "  ${DIM}  Frontend ($FE_PM2_NAME): $fe_status${NC}"

    if [[ -f "$LOGFILE" ]]; then
        echo ""
        echo -e "  ${BOLD}Last 5 deploy events:${NC}"
        grep "^===" "$LOGFILE" | tail -5 | while read -r line; do
            echo -e "  ${DIM}  $line${NC}"
        done
    fi
    echo ""
}

# ── Main ────────────────────────────────────────────────────────────────

DEPLOY_START=$(date +%s)
FAILED=0

# Handle special flags first
case "${1:-}" in
    --status|-s)
        validate
        do_status
        exit 0
        ;;
    --rollback|-r)
        validate
        do_rollback
        exit $?
        ;;
    --quick|-q)
        validate
        do_quick_deploy
        exit $?
        ;;
    --help|-h)
        echo ""
        echo -e "  ${BOLD}Anchor Point Advising — Deploy Script${NC}"
        echo ""
        echo -e "  ${BOLD}Usage:${NC}"
        echo "    bash scripts/deploy.sh              Full deploy (backend + frontend)"
        echo "    bash scripts/deploy.sh backend      Deploy backend only"
        echo "    bash scripts/deploy.sh frontend     Deploy frontend only"
        echo "    bash scripts/deploy.sh all          Deploy everything (default)"
        echo "    bash scripts/deploy.sh --quick      Pull + restart (no rebuild)"
        echo "    bash scripts/deploy.sh --rollback   Rollback to previous commit"
        echo "    bash scripts/deploy.sh --status     Show deployment info"
        echo ""
        exit 0
        ;;
esac

# ── Full Deploy ─────────────────────────────────────────────────────────

validate

echo ""
echo -e "  ${CYAN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "  ${CYAN}${BOLD}║     🚀  ANCHOR POINT — PRODUCTION DEPLOY    ║${NC}"
echo -e "  ${CYAN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${DIM}Target   : $DEPLOY_TARGET${NC}"
echo -e "  ${DIM}Branch   : $GIT_BRANCH${NC}"
echo -e "  ${DIM}Project  : $PROJECT_DIR${NC}"
echo -e "  ${DIM}Backend  : $BACKEND_DIR (port $BACKEND_PORT)${NC}"
echo -e "  ${DIM}Frontend : $FRONTEND_DIR (port $FRONTEND_PORT)${NC}"
separator

# Pull code
deploy_pull

# Ensure env files are valid
ensure_env_files || { log_fail "Env file check failed — aborting."; exit 1; }

# Deploy based on target
case "$DEPLOY_TARGET" in
    backend)
        deploy_backend  || ((FAILED++))
        ;;
    frontend)
        deploy_frontend || ((FAILED++))
        ;;
    all|*)
        deploy_backend  || ((FAILED++))
        deploy_frontend || ((FAILED++))
        ;;
esac

# Post-deploy
health_check
pm2 save

DEPLOY_END=$(date +%s)
DEPLOY_DURATION=$((DEPLOY_END - DEPLOY_START))

echo ""
separator
if [[ $FAILED -eq 0 ]]; then
    echo -e "  ${GREEN}${BOLD}🎉 Deploy complete! (${DEPLOY_DURATION}s)${NC}"
    if [[ -n "$DOMAIN_NAME" ]]; then
        echo -e "  ${DIM}  → https://${DOMAIN_NAME}${NC}"
    else
        local public_ip
        public_ip=$(curl -s --max-time 5 https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')
        echo -e "  ${DIM}  → http://${public_ip}${NC}"
    fi
else
    echo -e "  ${RED}${BOLD}💥 Deploy finished with $FAILED error(s). (${DEPLOY_DURATION}s)${NC}"
    echo -e "  ${DIM}  Log: $LOGFILE${NC}"
    echo -e "  ${DIM}  PM2: pm2 logs --lines 50${NC}"
    exit 1
fi
separator
echo ""
